### ISSUE TITLE
Integrate Google Map API

### ISSUE THREAD

**Issue by henry-lai** [henry-lai/Team8Agile#13]
Integrate google Maps API to the application

**Comment by henry-lai** [comment]
a Basic Interactive map has been added to the website

**Comment by tsween7** [comment]
Code to be reviewed

**Comment by tsween7** [comment]
Still code to be added for finding locations and distance

**Comment by henry-lai** [comment]
Map has been added on to web application. Just needs to have it find distance between hospitals

**Comment by henry-lai** [comment]
Issue is covered in new milestone
