### ISSUE TITLE
Find Cheapest, Closest and Best Entries and Keep Record

### ISSUE THREAD

**Issue by affyzal** [henry-lai/Team8Agile#15]
Find the Cheapest, Closest and Best Entries given by the search and and note that information in their DataRow

**Comment by affyzal** [comment]
List Label added to DataRow, which is a list to be Populated by all the titles that data entry holds. There can only be one cheapest,closest, and best Entry at the same time. One entry can hold all three titles if possible.

**Comment by tsween7** [comment]
code to be reviewed
