### ISSUE TITLE
Update GUI Design Implementation

### ISSUE THREAD

**Issue by affyzal** [henry-lai/Team8Agile#17]
Update the layout and design of the GUI to be consistent and more aesthetically balanced.

**Comment by henry-lai** [comment]
Details of What GUI elements needs to be updated:
- [ ] Placeholder text in search bar needs to describe what user is exactly searching for

- [ ] Separate search box. 1 for Code. 1 for Procedure

- [ ] Filter: allow user option to apply auto search (get user location) or allow him to enter it manually
 
- [ ] Use sliders for some filters

- [ ] Remove Procedure description from top hits search. User should already know the procedure, only show code.

- [ ] Have the maps side by side with search results

- [ ] After search, display filters next to the map

- [ ] Remove minimum price from filter

**Comment by henry-lai** [comment]
Closing this issue, as the requirements list above should be broken down into separate issues instead of into 1 single one.
