### ISSUE TITLE
get input and validate 

### ISSUE THREAD

**Issue by henry-lai** [henry-lai/Team8Agile#2]
Make a method to get user's input and validate them.

**Comment by henry-lai** [comment]
It validates the code of the record.
if code is not 3 digits, its rejected
if code is not numbers i.e. abc or def, it will be rejected
if code is left blank it is rejected

**Comment by henry-lai** [comment]
Need to clean input; remove special characters, prevent SQL injection

**Comment by tsween7** [comment]
Code to be reviewed

**Comment by tsween7** [comment]
Review approved
